import { ISendReportScrapingInputRequestMessage } from "src/ipc/types/message/variants/ReportScrapingMessage/variants/ReportScrapingInputRequestMessage/send/SendReportScrapingInputRequestMessage";

export type SendScrapingMessage = ISendReportScrapingInputRequestMessage